version: "3.9"
services:
  postgres:
    image: postgres:16
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "some_user"
      POSTGRES_PASSWORD: "some_password"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"